---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop container-redis-alpine
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm  container-redis-alpine
      ignore_errors: yes

    - name: remove used image
      command: docker rmi redis-alpine
      ignore_errors: yes

    - name: build docker image from dockerfile
      command: docker build -t redis-alpine .

    - name: create tag to image
      command: docker tag redis-alpine  atefelshenawy/redis-alpine

    - name: push image to dockerhub
      command: docker push atefelshenawy/redis-alpine

    - name: run container from image
      command: docker run -d --name container-redis-alpine -p 6379 redis-apine